#constantes.py
# Player
PLAYER_SPEED = 3
PLAYER_HEALTH = 100
PLAYER_START_AMMO = 50
PLAYER_START_COINS = 0
PLAYER_START_MEDKITS = 0

# Projéteis
BULLET_SPEED = 20
BULLET_DAMAGE = 25
BULLET_LIFETIME = 2500  # pixels

# Zumbis
ZOMBIE_HEALTH = 50
ZOMBIE_SPEED = 1

# Obstáculos
FLOR_HEALTH = 30
CONTAINER_HEALTH = 100

# Cadência de tiro (ms)
FIRE_RATE = 250

# Respawn
ZOMBIE_RESPAWN_INTERVAL = 3000  # em ms